apiVersion: apps/v1
kind: Deployment
metadata:
  name: quotes-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quotes-app
  template:
    metadata:
      labels:
        app: quotes-app
    spec:
      containers:
      - name: quotes-app
        image: atuljkamble/quotes-app:latest
        ports:
        - containerPort: 5000
