apiVersion: v1
kind: Service
metadata:
  name: minikube-quotes-service
spec:
  type: LoadBalancer
  selector:
    app: minikube-quotes
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
